import webpush from "web-push";

/**
 * Generates a VAPID key pair.
 *
 *   pnpm vapid:keys
 *
 * Run ONCE per deployment and keep the result. Regenerating invalidates every
 * existing subscription: a browser's `PushSubscription` is bound to the public
 * key it was created with, so a new pair silently stops every already-
 * subscribed device from receiving anything, with no error anywhere — the push
 * service simply rejects the send.
 *
 * Prints to stdout in `.env` form, and prints nothing else, so the output can
 * be appended to a file. The private key is a SECRET: it signs every push, and
 * a copy of it lets anybody send notifications that appear to come from this
 * site. It must never be committed and never gain a `NEXT_PUBLIC_` prefix.
 */

const keys = webpush.generateVAPIDKeys();

console.log("# Generated by `pnpm vapid:keys`. Keep the private key secret.");
console.log(`NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}`);
console.log(`VAPID_PRIVATE_KEY=${keys.privateKey}`);
console.log("# Who a push service should contact about our traffic.");
console.log("VAPID_SUBJECT=mailto:you@example.com");
